### ISSUE TITLE
Reason for only allowing direct references to in-scope values?

### ISSUE THREAD

**Issue by simonihmig** [emberjs/babel-plugin-ember-template-compilation#14]
This [assertion](https://github.com/emberjs/babel-plugin-ember-template-compilation/blob/main/src/expression-parser.ts#L103) seems to allow only scopes defined as `{ foo }` or `{ foo: foo }`, but not `{ foo: bar }`. I wonder why that is?

The problem I was running into:

I am using [rollup-plugin-glimmer-template-tag](https://github.com/NullVoxPopuli/rollup-plugin-glimmer-template-tag) and `rollup-plugin-ts` in a v2 addon, I was importing the default export of a component `HeadlessFormFieldComponent` under a shorter name, like this:

```js
import FieldComponent from './field';
```

But during the compilation process (`/dist` output of v2 addon), this gets **implicitly** transformed to something like this:

```js
import HeadlessFormFieldComponent from './field';

setComponentTemplate(precompileTemplate(`...`, {
  strictMode: true,
  scope: () => ({
    FieldComponent: HeadlessFormFieldComponent
  })
```

Idk why this is being done, but it seems perfectly valid from a pure JS standpoint. But the babel plugin then throws `Scope objects for precompileTemplate may only contain direct references to in-scope values, e.g. { FieldComponent } or { FieldComponent: FieldComponent }`

Similar things happen when you import by assigning an alias, like 

```js
import { EnsureSafeComponentHelper as ensureSafeComponent } from '@embroider/util';
```

...which gets rewritten to

```js
import { EnsureSafeComponentHelper } from '@embroider/util';

setComponentTemplate(precompileTemplate(`...`, {
  strictMode: true,
  scope: () => ({
    ensureSafeComponent: EnsureSafeComponentHelper
  })
```

**Comment by candunaj** [comment]
This was solved with the following PRs and released in 2.0.2
https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/17
https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/19
