### ISSUE TITLE
Potential issue with 2.0.1

### ISSUE THREAD

**Issue by runspired** [emberjs/babel-plugin-ember-template-compilation#18]
EmberData's no-lockfile test scenario hits this issue when picking up the new release:

```
tests/request test:   - errorType: [undefined]
tests/request test:   - location:
tests/request test:     - column: [undefined]
tests/request test:     - file: [undefined]
tests/request test:     - line: [undefined]
tests/request test:   - message: Cannot find module 'babel-plugin-ember-template-compilation'
tests/request test: Require stack:
tests/request test: - /home/runner/work/data/data/node_modules/.pnpm/ember-auto-import@2.6.2_webpack@5.77.0/node_modules/ember-auto-import/js/package.js
tests/request test: - /home/runner/work/data/data/node_modules/.pnpm/ember-auto-import@2.6.2_webpack@5.77.0/node_modules/ember-auto-import/js/auto-import.js
tests/request test: - /home/runner/work/data/data/node_modules/.pnpm/ember-auto-import@2.6.2_webpack@5.77.0/node_modules/ember-auto-import/js/index.js
```

**Comment by mansona** [comment]
That's actually an issue with ember-auto-import not having the correct dependencies declared. I don't know exactly why it wasn't caught in the ember-auto-import test suite but 🤷 

There is already a fix for it https://github.com/ef4/ember-auto-import/pull/576 that we just need to merge and release 👍

**Comment by runspired** [comment]
@mansona I think this is because ember-auto-import is using `npm` and not `pnpm` and thus does not have isolated node_modules trees that catch mistakes that are papered over by auto-install of peers or auto-hoisting.
